export * from './IconTrash'
export * from './IconInfo'
export * from './IconSearch'
export * from './IconClose'
export * from './IconQuestion'
export * from './IconUpload'
export * from './IconCollection'
export * from './IconProduct'
export * from './IconWebpage'
export * from './IconPlus'
export * from './IconEye'
export * from './IconPenEdit'
export * from './IconPenEdit2'
export * from './IconPlainText'
export * from './IconArrowLeft'
export * from './IconArrowRight'
export * from './IconArrow2Down'
export * from './IconDuplicate'
export * from './IconChevronRight'
export * from './IconCopy'

export * from './IconCode'

export * from './IconMenu'

export * from './Icon2DotsMark'
export * from './IconDrag'
