export const ACCESS_TOKEN = 'token'
export const REFRESH_TOKEN = 'refresh_token'
export const APP_KEY = 'appKey'
export const THIRT_PARTY = 'thirt_party'
export const IMPERSONATED = 'impersonated'
export const STORE_CODE = 'store_code'
export const CURRENCY_CODE = 'currency_code'

export const FORMAT_DATE = 'MMM DD'

export const MOBILE_WIDTH = 390

export const DEFAULT_DESCRIPTION =
  'Dolore commodo cupidatat commodo veniam. Cillum pariatur qui esse magna commodo ad laborum ex enim velit commodo culpa.'

export const SOCIAL_MEDIA_TYPE = [
  {
    packageName: 'com.whatsapp',
    urlScheme: 'whatsapp',
    name: 'WhatsApp',
  },
  {
    packageName: 'com.facebook.katana',
    urlScheme: 'fb',
    name: 'Facebook',
  },
  {
    packageName: 'com.facebook.orca',
    urlScheme: 'fb-messenger',
    name: 'Facebook Messenger',
  },
  {
    packageName: 'com.skype.raider',
    urlScheme: 'skype',
    name: 'Skype',
  },
  {
    packageName: 'com.tencent.mm',
    urlScheme: 'weixin',
    name: 'WeChat',
  },
  {
    packageName: 'com.snapchat.android',
    urlScheme: 'snapchat',
    name: 'Snapchat',
  },
  {
    packageName: 'com.twitter.android',
    urlScheme: 'twitter',
    name: 'Twitter',
  },
  {
    packageName: 'com.google.android.youtube',
    urlScheme: 'youtube',
    name: 'Youtube',
  },
  {
    packageName: 'com.instagram.android',
    urlScheme: 'instagram',
    name: 'Instagram',
  },
  {
    packageName: 'com.spotify.mobile.android.ui',
    urlScheme: 'spotify',
    name: 'Spotify',
  },
  {
    packageName: 'com.pinterest',
    urlScheme: 'pinterest',
    name: 'Pinterest',
  },
  { packageName: 'com.ubercab', urlScheme: 'uber', name: 'Uber' },
  {
    packageName: 'com.amazon.mShop.android.shopping',
    urlScheme: 'amazon',
    name: 'Amazon',
  },
  {
    packageName: 'com.soundcloud.android',
    urlScheme: 'soundcloud',
    name: 'Soundcloud',
  },
  {
    packageName: 'com.google.android.apps.maps',
    urlScheme: 'comgooglemaps',
    name: 'Google Maps',
  },
  {
    packageName: 'com.google.android.talk',
    urlScheme: 'com.google.hangouts',
    name: 'Google Hangouts',
  },
  {
    packageName: 'com.yahoo.mobile.client.android.flickr',
    urlScheme: 'flickr',
    name: 'Flickr',
  },
  {
    packageName: 'com.linkedin.android',
    urlScheme: 'linkedin',
    name: 'LinkedIn',
  },
]

export const TAGS = [
  'Activity tracker',
  'Air travel',
  'Art & design',
  'Audio recorder',
  'Audiobook',
  'Auto & vehicles',
  'Baby care',
  'Barcode scanner',
  'Baseball',
  'Beauty',
  'Blog',
  'Boating',
  'Books & reference',
  'Bus',
  'Business',
  'Calculator',
  'Calendar',
  'Call-recording',
  'Caller ID',
  'Camera',
  'Car rental',
  "Children's literature",
  'Clock, alarm & timer',
  'Color by number',
  'Coloring book',
  'Comics',
  'Communication',
  'Computer-aided design',
  'Cosmetics',
  'Cryptocurrency',
  'Dating',
  'Dictionary',
  'Dieting',
  "Driver's education",
  'E-reader',
  'Early childhood education',
  'Education',
  'Email',
  'Emoji',
  'Emoticon',
  'Encyclopedia',
  'Entertainment',
  'Events',
  'Fashion',
  'Finance',
  'Flashlight',
  'Food & drink',
  'Food delivery',
  'Grammar',
  'Guitar',
  'Hairstyle',
  'Health & fitness',
  'Home automation',
  'Home insurance',
  'Horoscope',
  'Horse racing',
  'Hotels & vacation rental',
  'House & home',
  'Humor',
  'Insurance',
  'Interior design',
  'Investment',
  'Job interview',
  'Job seeking',
  'Joke',
  'Karaoke',
  'Keyboard',
  'Language education',
  'Launcher',
  'Lifestyle',
  'Live television',
  'Loan',
  'Lock screen',
  'Loyalty program',
  'Lyrics',
  'Maps & navigation',
  'Martial arts',
  'Mathematics',
  'Measurement',
  'Medical',
  'Meditation',
  'Meet new people',
  'Mirror',
  'Mobile banking',
  'Mobile payment',
  'Movie',
  'Movie tickets, reviews & listings',
  'Music & audio',
  'Music instrument',
  'Network connectivity',
  'News & magazines',
  'News aggregator',
  'Notebook',
  'Painting',
  'Parenting',
  'Password manager',
  'Personal assistant',
  'Personal finance',
  'Personalization',
  'Photo editor',
  'Photo frame',
  'Prank',
  'Primary education',
  'Privacy & security',
  'Productivity',
  'Professional network service',
  'Pronunciation',
  'Public transport',
  'Racing',
  'Racquet sports',
  'Radio',
  'Recipe',
  'Religious text',
  'Remote control',
  'Restaurant',
  'Resume',
  'Ringtone',
  'Rugby',
  'Running',
  'Science education',
  'Self-help',
  'Shopping',
  'Skiing',
  'Sleep',
  'Social',
  'Sound effect',
  'Speedometer',
  'Sports',
  'Sports coaching',
  'Study guide',
  'TV',
  'TV guide',
  'Taxi & rideshare',
  'Tennis',
  'Test preparation',
  'Text messaging',
  'Theme',
  'Tools',
  'Train',
  'Travel & local',
  'Travel guide',
  'Vehicle insurance',
  'Vehicle maintenance',
  'Vehicle shopping',
  'Video call',
  'Video download',
  'Video editing',
  'Video player',
  'Video players & editors',
  'Video streaming',
  'Virtual private network (VPN)',
  'Virtual reality',
  'Wallpaper',
  'Weather',
  'Web browser',
  'Weight loss',
  'Wi-fi',
  'Wireless service provider',
  'Workout',
  'Yoga',
]

export const CATEGORIES = [
  'Books',
  'Business',
  'Developer Tools',
  'Education',
  'Entertainment',
  'Finance',
  'Food & Drink',
  'Games',
  'Graphics & Design',
  'Health & Fitness',
  'Lifestyle',
  'Magazines & Newspapers',
  'Medical',
  'Music',
  'Navigation',
  'News',
  'Photo & Video',
  'Productivity',
  'Reference',
  'Shopping',
  'Social Networking',
  'Sports',
  'Stickers',
  'Travel',
  'Utilities',
  'Weather',
]

export const COUNTRIES = [
  {
    title: 'All',
    value: 'All',
    key: 'All',
    children: [
      {
        title: 'The United States and Canada',
        value: 'The United States and Canada',
        key: 'The United States and Canada',
        children: [
          {
            title: 'Canada',
            value: 'Canada',
            key: 'Canada',
          },
          {
            title: 'United States',
            value: 'United States',
            key: 'United States',
          },
        ],
      },
      {
        title: 'Europe',
        value: 'Europe',
        key: 'Europe',
        children: [
          { title: 'Albania', value: 'Albania', key: 'Albania' },
          { title: 'Austria', value: 'Austria', key: 'Austria' },
          { title: 'Belarus', value: 'Belarus', key: 'Belarus' },
          { title: 'Belgium', value: 'Belgium', key: 'Belgium' },
          { title: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina', key: 'Bosnia and Herzegovina' },
          { title: 'Bulgaria', value: 'Bulgaria', key: 'Bulgaria' },
          { title: 'Croatia', value: 'Croatia', key: 'Croatia' },
          { title: 'Cyprus', value: 'Cyprus', key: 'Cyprus' },
          { title: 'Czech Republic', value: 'Czech Republic', key: 'Czech Republic' },
          { title: 'Denmark', value: 'Denmark', key: 'Denmark' },
          { title: 'Estonia', value: 'Estonia', key: 'Estonia' },
          { title: 'Finland', value: 'Finland', key: 'Finland' },
          { title: 'France', value: 'France', key: 'France' },
          { title: 'Germany', value: 'Germany', key: 'Germany' },
          { title: 'Greece', value: 'Greece', key: 'Greece' },
          { title: 'Hungary', value: 'Hungary', key: 'Hungary' },
          { title: 'Iceland', value: 'Iceland', key: 'Iceland' },
          { title: 'Ireland', value: 'Ireland', key: 'Ireland' },
          { title: 'Italy', value: 'Italy', key: 'Italy' },
          { title: 'Kosovo', value: 'Kosovo', key: 'Kosovo' },
          { title: 'Latvia', value: 'Latvia', key: 'Latvia' },
          { title: 'Lithuania', value: 'Lithuania', key: 'Lithuania' },
          { title: 'Luxembourg', value: 'Luxembourg', key: 'Luxembourg' },
          { title: 'Malta', value: 'Malta', key: 'Malta' },
          { title: 'Moldova', value: 'Moldova', key: 'Moldova' },
          { title: 'Montenegro', value: 'Montenegro', key: 'Montenegro' },
          { title: 'Netherlands', value: 'Netherlands', key: 'Netherlands' },
          { title: 'North Macedonia', value: 'North Macedonia', key: 'North Macedonia' },
          { title: 'Norway', value: 'Norway', key: 'Norway' },
          { title: 'Poland', value: 'Poland', key: 'Poland' },
          { title: 'Portugal', value: 'Portugal', key: 'Portugal' },
          { title: 'Romania', value: 'Romania', key: 'Romania' },
          { title: 'Russia', value: 'Russia', key: 'Russia' },
          { title: 'Serbia', value: 'Serbia', key: 'Serbia' },
          { title: 'Slovakia', value: 'Slovakia', key: 'Slovakia' },
          { title: 'Slovenia', value: 'Slovenia', key: 'Slovenia' },
          { title: 'Spain', value: 'Spain', key: 'Spain' },
          { title: 'Sweden', value: 'Sweden', key: 'Sweden' },
          { title: 'Switzerland', value: 'Switzerland', key: 'Switzerland' },
          { title: 'Türkiye', value: 'Türkiye', key: 'Türkiye' },
          { title: 'Ukraine', value: 'Ukraine', key: 'Ukraine' },
          { title: 'United Kingdom', value: 'United Kingdom', key: 'United Kingdom' },
        ],
      },
      {
        title: 'Africa, Middle East, and India',
        value: 'Africa, Middle East, and India',
        key: 'Africa, Middle East, and India',
        children: [
          { title: 'Afghanistan', value: 'Afghanistan', key: 'Afghanistan' },
          { title: 'Algeria', value: 'Algeria', key: 'Algeria' },
          { title: 'Angola', value: 'Angola', key: 'Angola' },
          { title: 'Armenia', value: 'Armenia', key: 'Armenia' },
          { title: 'Azerbaijan', value: 'Azerbaijan', key: 'Azerbaijan' },
          { title: 'Bahrain', value: 'Bahrain', key: 'Bahrain' },
          { title: 'Benin', value: 'Benin', key: 'Benin' },
          { title: 'Botswana', value: 'Botswana', key: 'Botswana' },
          { title: 'Burkina Faso', value: 'Burkina Faso', key: 'Burkina Faso' },
          { title: 'Cameroon', value: 'Cameroon', key: 'Cameroon' },
          { title: 'Cape Verde', value: 'Cape Verde', key: 'Cape Verde' },
          { title: 'Chad', value: 'Chad', key: 'Chad' },
          {
            title: 'Congo, Democratic Republic of the',
            value: 'Congo, Democratic Republic of the',
            key: 'Congo, Democratic Republic of the',
          },
          { title: 'Congo, Republic of the', value: 'Congo, Republic of the', key: 'Congo, Republic of the' },
          { title: 'Côte d’Ivoire', value: 'Côte d’Ivoire', key: 'Côte d’Ivoire' },
          { title: 'Egypt', value: 'Egypt', key: 'Egypt' },
          { title: 'Eswatini', value: 'Eswatini', key: 'Eswatini' },
          { title: 'Gabon', value: 'Gabon', key: 'Gabon' },
          { title: 'Gambia', value: 'Gambia', key: 'Gambia' },
          { title: 'Georgia', value: 'Georgia', key: 'Georgia' },
          { title: 'Ghana', value: 'Ghana', key: 'Ghana' },
          { title: 'Guinea-Bissau', value: 'Guinea-Bissau', key: 'Guinea-Bissau' },
          { title: 'India', value: 'India', key: 'India' },
          { title: 'Iraq', value: 'Iraq', key: 'Iraq' },
          { title: 'Israel', value: 'Israel', key: 'Israel' },
          { title: 'Jordan', value: 'Jordan', key: 'Jordan' },
          { title: 'Kenya', value: 'Kenya', key: 'Kenya' },
          { title: 'Kuwait', value: 'Kuwait', key: 'Kuwait' },
          { title: 'Lebanon', value: 'Lebanon', key: 'Lebanon' },
          { title: 'Liberia', value: 'Liberia', key: 'Liberia' },
          { title: 'Libya', value: 'Libya', key: 'Libya' },
          { title: 'Madagascar', value: 'Madagascar', key: 'Madagascar' },
          { title: 'Malawi', value: 'Malawi', key: 'Malawi' },
          { title: 'Mali', value: 'Mali', key: 'Mali' },
          { title: 'Mauritania', value: 'Mauritania', key: 'Mauritania' },
          { title: 'Mauritius', value: 'Mauritius', key: 'Mauritius' },
          { title: 'Morocco', value: 'Morocco', key: 'Morocco' },
          { title: 'Mozambique', value: 'Mozambique', key: 'Mozambique' },
          { title: 'Namibia', value: 'Namibia', key: 'Namibia' },
          { title: 'Niger', value: 'Niger', key: 'Niger' },
          { title: 'Nigeria', value: 'Nigeria', key: 'Nigeria' },
          { title: 'Oman', value: 'Oman', key: 'Oman' },
          { title: 'Qatar', value: 'Qatar', key: 'Qatar' },
          { title: 'Rwanda', value: 'Rwanda', key: 'Rwanda' },
          { title: 'São Tomé and Príncipe', value: 'São Tomé and Príncipe', key: 'São Tomé and Príncipe' },
          { title: 'Saudi Arabia', value: 'Saudi Arabia', key: 'Saudi Arabia' },
          { title: 'Senegal', value: 'Senegal', key: 'Senegal' },
          { title: 'Seychelles', value: 'Seychelles', key: 'Seychelles' },
          { title: 'Sierra Leone', value: 'Sierra Leone', key: 'Sierra Leone' },
          { title: 'South Africa', value: 'South Africa', key: 'South Africa' },
          { title: 'Tanzania', value: 'Tanzania', key: 'Tanzania' },
          { title: 'Tunisia', value: 'Tunisia', key: 'Tunisia' },
          { title: 'Uganda', value: 'Uganda', key: 'Uganda' },
          { title: 'United Arab Emirates', value: 'United Arab Emirates', key: 'United Arab Emirates' },
          { title: 'Yemen', value: 'Yemen', key: 'Yemen' },
          { title: 'Zambia', value: 'Zambia', key: 'Zambia' },
          { title: 'Zimbabwe', value: 'Zimbabwe', key: 'Zimbabwe' },
        ],
      },
      {
        title: 'Latin America and the Caribbean',
        value: 'Latin America and the Caribbean',
        key: 'Latin America and the Caribbean',
        children: [
          { title: 'Anguilla', value: 'Anguilla', key: 'Anguilla' },
          { title: 'Antigua and Barbuda', value: 'Antigua and Barbuda', key: 'Antigua and Barbuda' },
          { title: 'Argentina', value: 'Argentina', key: 'Argentina' },
          { title: 'Bahamas', value: 'Bahamas', key: 'Bahamas' },
          { title: 'Barbados', value: 'Barbados', key: 'Barbados' },
          { title: 'Belize', value: 'Belize', key: 'Belize' },
          { title: 'Bermuda', value: 'Bermuda', key: 'Bermuda' },
          { title: 'Bolivia', value: 'Bolivia', key: 'Bolivia' },
          { title: 'Brazil', value: 'Brazil', key: 'Brazil' },
          { title: 'British Virgin Islands', value: 'British Virgin Islands', key: 'British Virgin Islands' },
          { title: 'Cayman Islands', value: 'Cayman Islands', key: 'Cayman Islands' },
          { title: 'Chile', value: 'Chile', key: 'Chile' },
          { title: 'Colombia', value: 'Colombia', key: 'Colombia' },
          { title: 'Costa Rica', value: 'Costa Rica', key: 'Costa Rica' },
          { title: 'Dominica', value: 'Dominica', key: 'Dominica' },
          { title: 'Dominican Republic', value: 'Dominican Republic', key: 'Dominican Republic' },
          { title: 'Ecuador', value: 'Ecuador', key: 'Ecuador' },
          { title: 'El Salvador', value: 'El Salvador', key: 'El Salvador' },
          { title: 'Grenada', value: 'Grenada', key: 'Grenada' },
          { title: 'Guatemala', value: 'Guatemala', key: 'Guatemala' },
          { title: 'Guyana', value: 'Guyana', key: 'Guyana' },
          { title: 'Honduras', value: 'Honduras', key: 'Honduras' },
          { title: 'Jamaica', value: 'Jamaica', key: 'Jamaica' },
          { title: 'Mexico', value: 'Mexico', key: 'Mexico' },
          { title: 'Montserrat', value: 'Montserrat', key: 'Montserrat' },
          { title: 'Nicaragua', value: 'Nicaragua', key: 'Nicaragua' },
          { title: 'Panama', value: 'Panama', key: 'Panama' },
          { title: 'Paraguay', value: 'Paraguay', key: 'Paraguay' },
          { title: 'Peru', value: 'Peru', key: 'Peru' },
          { title: 'St. Kitts and Nevis', value: 'St. Kitts and Nevis', key: 'St. Kitts and Nevis' },
          { title: 'St. Lucia', value: 'St. Lucia', key: 'St. Lucia' },
          {
            title: 'St. Vincent and the Grenadines',
            value: 'St. Vincent and the Grenadines',
            key: 'St. Vincent and the Grenadines',
          },
          { title: 'Suriname', value: 'Suriname', key: 'Suriname' },
          { title: 'Trinidad and Tobago', value: 'Trinidad and Tobago', key: 'Trinidad and Tobago' },
          { title: 'Turks and Caicos Islands', value: 'Turks and Caicos Islands', key: 'Turks and Caicos Islands' },
          { title: 'Uruguay', value: 'Uruguay', key: 'Uruguay' },
          { title: 'Venezuela', value: 'Venezuela', key: 'Venezuela' },
        ],
      },
      {
        title: 'Asia Pacific',
        value: 'Asia Pacific',
        key: 'Asia Pacific',
        children: [
          { title: 'Australia', value: 'Australia', key: 'Australia' },
          { title: 'Bhutan', value: 'Bhutan', key: 'Bhutan' },
          { title: 'Brunei', value: 'Brunei', key: 'Brunei' },
          { title: 'Cambodia', value: 'Cambodia', key: 'Cambodia' },
          { title: 'China mainland', value: 'China mainland', key: 'China mainland' },
          { title: 'Fiji', value: 'Fiji', key: 'Fiji' },
          { title: 'Hong Kong', value: 'Hong Kong', key: 'Hong Kong' },
          { title: 'Indonesia', value: 'Indonesia', key: 'Indonesia' },
          { title: 'Japan', value: 'Japan', key: 'Japan' },
          { title: 'Kazakhstan', value: 'Kazakhstan', key: 'Kazakhstan' },
          { title: 'Korea, Republic of', value: 'Korea, Republic of', key: 'Korea, Republic of' },
          { title: 'Kyrgyzstan', value: 'Kyrgyzstan', key: 'Kyrgyzstan' },
          { title: 'Laos', value: 'Laos', key: 'Laos' },
          { title: 'Macau', value: 'Macau', key: 'Macau' },
          { title: 'Malaysia', value: 'Malaysia', key: 'Malaysia' },
          { title: 'Maldives', value: 'Maldives', key: 'Maldives' },
          { title: 'Micronesia', value: 'Micronesia', key: 'Micronesia' },
          { title: 'Mongolia', value: 'Mongolia', key: 'Mongolia' },
          { title: 'Myanmar', value: 'Myanmar', key: 'Myanmar' },
          { title: 'Nauru', value: 'Nauru', key: 'Nauru' },
          { title: 'Nepal', value: 'Nepal', key: 'Nepal' },
          { title: 'New Zealand', value: 'New Zealand', key: 'New Zealand' },
          { title: 'Pakistan', value: 'Pakistan', key: 'Pakistan' },
          { title: 'Palau', value: 'Palau', key: 'Palau' },
          { title: 'Papua New Guinea', value: 'Papua New Guinea', key: 'Papua New Guinea' },
          { title: 'Philippines', value: 'Philippines', key: 'Philippines' },
          { title: 'Singapore', value: 'Singapore', key: 'Singapore' },
          { title: 'Solomon Islands', value: 'Solomon Islands', key: 'Solomon Islands' },
          { title: 'Sri Lanka', value: 'Sri Lanka', key: 'Sri Lanka' },
          { title: 'Taiwan', value: 'Taiwan', key: 'Taiwan' },
          { title: 'Tajikistan', value: 'Tajikistan', key: 'Tajikistan' },
          { title: 'Thailand', value: 'Thailand', key: 'Thailand' },
          { title: 'Tonga', value: 'Tonga', key: 'Tonga' },
          { title: 'Turkmenistan', value: 'Turkmenistan', key: 'Turkmenistan' },
          { title: 'Uzbekistan', value: 'Uzbekistan', key: 'Uzbekistan' },
          { title: 'Vanuatu', value: 'Vanuatu', key: 'Vanuatu' },
          { title: 'Vietnam', value: 'Vietnam', key: 'Vietnam' },
        ],
      },
    ],
  },
]

export const CHARTS = {
  Overview: {
    Installs: {
      title: 'Installs',
      desc: 'The number of app installs',
    },
    Sessions: {
      title: 'Sessions',
      desc: 'The number of app sessions',
    },
    Revenue: {
      title: 'Revenue',
      desc: 'The sum of all order amounts generated from the app, regardless of canceled orders',
    },
    Conversion: {
      title: 'Conversion',
      desc: 'The install-to-purchase conversion rate',
    },
    ActiveUsers: {
      title: 'Active users',
      desc: 'The number of unique app users who have opened the app at least once in the last 24 hours and 30 days',
    },
    UserStickiness: {
      title: 'User stickiness',
      desc: 'The ratio of daily active users to monthly active users, used to measure how often users returned to the app',
    },
    SignedUpUsers: {
      title: 'Signed-up users',
      desc: 'The number of app users who have signed up for an account',
    },
    AppActivity: {
      title: 'App activity',
      desc: 'The density of app sessions by day and by hour',
    },
    TimeToFirstPurchase: {
      title: 'Time to first purchase',
      desc: 'The average number of days it took for an app user to make their first purchase after installing the app',
    },
    TimeBetweenPurchases: {
      title: 'Time between purchases',
      desc: 'The average number of days an app user took between making two purchases',
    },
  },
  Acquisition: {
    AppInstalls: {
      title: 'App installs',
      desc: 'The number of app installs',
    },
    AppInstallsByPlatform: {
      title: 'App installs by platform',
      desc: 'The percentage of app installs by device type',
    },
    AppOpenRate: {
      title: 'App open rate',
      desc: 'The percentage of the customer base that opens the app at least once for the chosen period',
    },
    AppOpensBySource: {
      title: 'App opens by source',
      desc: 'The number of app opens and the source of opens',
    },
    AppSessions: {
      title: 'App sessions',
      desc: 'The number of all sessions that occurred in the app',
    },
    SessionsBySource: {
      title: 'Sessions by source',
      desc: 'The source of app sessions',
    },
    AverageNumberOfSessions: {
      title: 'Average number of sessions',
      desc: 'The average number of app sessions per active user',
    },
    AverageSessionLength: {
      title: 'Average session length',
      desc: 'The average length of an app session',
    },
  },
  Revenue: {
    AppRevenue: {
      title: 'App revenue',
      desc: 'The sum of all order amounts generated from the app, regardless of canceled orders',
    },
    TotalOrders: {
      title: 'Total orders',
      desc: 'The number of orders generated from the app',
    },
    AverageOrderValue: {
      title: 'Average order value',
      desc: 'The average amount of money users spent on an order',
    },
    OrdersBySource: {
      title: 'Orders by source',
      desc: 'The sources users used before entering the app and making an order',
    },
    AverageRevenuePerUser: {
      title: 'Average revenue per user',
      desc: 'The average amount of revenue generated by each user, whether they made a purchase or not',
    },
    AverageRevenuePerPayingUser: {
      title: 'Average revenue per paying user',
      desc: 'The average amount of revenue per user who made a purchase',
    },
    RevenueByNewVsReturningUsers: {
      title: 'Revenue by new vs returning users',
      desc: 'A comparison between the revenue generated by new and returning users',
    },
    RevenueByCouponCode: {
      title: 'Revenue by coupon code',
      desc: 'A comparison between the revenue generated with and without coupon codes',
    },
  },
  Retention: {
    AppUsers: {
      title: 'App users',
      desc: 'The number of app users for the chosen period, separated by new and returning users',
    },
    UserGrowthRate: {
      title: 'User growth rate',
      desc: 'The percentage of new users an app gains for the chosen period. The growth rate from zero is considered 100%.',
    },
    RetentionRate: {
      title: 'Retention rate',
      desc: 'The percentage of new users who returned to the app on Day 1 and Day 30 after their first launch',
    },
    CustomerLifetimeValue: {
      title: 'Customer lifetime value',
      desc: 'The average amount of money your business can generate from users over 3 years',
    },
    AverageOrderFrequency: {
      title: 'Average order frequency',
      desc: 'The average number of orders placed by an individual user',
    },
    RepurchaseRate: {
      title: 'Repurchase rate',
      desc: 'The percentage of users who have purchased via the app more than once for the chosen period',
    },
    AppUninstalls: {
      title: 'App uninstalls',
      desc: 'The number of app uninstalls for the chosen period, separated by device type',
    },
    ChurnRate: {
      title: 'Churn rate',
      desc: 'The percentage of users who uninstall an app for the chosen period',
    },
  },
  PurchaseJourney: {
    PurchaseFunnel: {
      title: 'Purchase funnel',
      desc: 'The customer purchase journey, calculated based on app sessions',
    },
    CartAbandonmentRate: {
      title: 'Cart abandonment rate',
      desc: 'The percentage of shopping carts that did not convert to an order',
    },
    TopSearchKeywords: {
      title: 'Top searched keywords',
      desc: 'The top 10 keywords that were searched the most',
    },
    TopCategoryViews: {
      title: 'Top viewed categories',
      desc: 'The top 10 product categories that were viewed the most',
    },
    TopProducts: {
      title: 'Top products',
      desc: 'The top 10 products that performed the best',
    },
  },
  Notifications: {
    NotificationFunnel: {
      title: 'Delivery funnel',
      desc: 'The notification delivery funnel',
    },
    OptInRate: {
      title: 'Opt-in rate',
      desc: 'The percentage of users who allowed push notifications for the app',
    },
    ClickThroughRate: {
      title: 'Open rate',
      desc: 'The percentage of push notifications that were opened, out of those received by devices',
    },
    TotalPushPerformance: {
      title: 'Overall push performance',
      desc: 'The overall performance of push notifications as a sales channel',
    },
    IndividualPushPerformance: {
      title: 'Individual push performance',
      desc: 'A detailed report on the performance of each push notification',
    },
  },

  OverviewV2: {
    PeriodDownloads: {
      title: 'Period downloads',
      desc: 'Count of app downloads over the chosen period, excluding instances without subsequent app openings',
    },
    LifetimeDownloads: {
      title: 'Lifetime downloads',
      desc: "Count of app downloads since the App Store's launch up to yesterday, excluding instances without subsequent app openings",
    },
    ActiveUsers: {
      title: 'Active users',
      desc: 'Count of unique users initiating at least one session',
    },
    ActiveUsers2: {
      title: 'Active users',
      desc: 'Count of active users in the last 24 hours (Daily Active Users - DAU) and in the last 30 days (Monthly Active Users - MAU)',
    },
    UserActivity: {
      title: 'User activity',
      desc: 'User activity by app sessions, plotted across days and hours',
    },
    Orders: {
      title: 'Orders',
      desc:
        'Count of eligible orders with the following order status:' +
        '<ul class="pl-5 py-2 m-0"><li>Awaiting Fulfillment</li>' +
        '<li>Awaiting Pickup</li>' +
        '<li>Awaiting Shipment</li>' +
        '<li>Partially Shipped</li>' +
        '<li>Shipped</li>' +
        '<li>Completed</li>' +
        '<li>Refunded</li>' +
        '<li>Partially Refunded</li></ul>',
    },
    Revenue: {
      title: 'Revenue',
      desc:
        'Sum of the grand total, including taxes, shipping, and discounts, from eligible orders with the following order status:' +
        '<ul class="pl-5 py-2 m-0"><li>Awaiting Fulfillment</li>' +
        '<li>Awaiting Pickup</li>' +
        '<li>Awaiting Shipment</li>' +
        '<li>Partially Shipped</li>' +
        '<li>Shipped</li>' +
        '<li>Completed</li>' +
        '<li>Refunded</li>' +
        '<li>Partially Refunded</li></ul>',
    },
    AOV: {
      title: 'Average order value',
      desc: 'Average monetary value of eligible orders placed by users',
    },
    PushOptIn: {
      title: 'Push opt-in',
      desc: 'Percentage of users opting to receive push notifications',
    },
  },
}
